---
abstract: 'IO::Async support for the AMQP protocol'
author:
  - 'Tom Molesworth <cpan@perlsite.co.uk>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Fatal: '0.010'
  Test::HexString: '0'
  Test::MemoryGrowth: '0'
  Test::More: '0.98'
  Test::Refcount: '0.07'
  perl: '5.014000'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-AMQP
requires:
  Class::ISA: '0'
  File::ShareDir: '0'
  Future: '0.30'
  IO::Async: '0.63'
  IO::Socket::IP: '0'
  List::UtilsBy: '0'
  Mixin::Event::Dispatch: '1.006'
  Net::AMQP: '0.06'
  Time::HiRes: '0'
  curry: '0'
  parent: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Async-AMQP
  homepage: http://search.cpan.org/dist/Net-Async-AMQP/
version: '0.018'
