---
abstract: 'IO::Async support for the AMQP protocol'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::CheckDeps: 0.010
  Test::Fatal: 0.010
  Test::More: 0.98
  Test::Refcount: 0.07
  perl: 5.010001
configure_requires:
  ExtUtils::MakeMaker: 6.48
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-AMQP
requires:
  Class::ISA: 0
  Closure::Explicit: 0
  File::ShareDir: 0
  Future: 0.15
  IO::Async: 0.50
  List::UtilsBy: 0
  Mixin::Event::Dispatch: 1.000
  Net::AMQP: 0.04
  Try::Tiny: 0
  curry: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Async-AMQP
  homepage: http://search.cpan.org/dist/Net-Async-AMQP/
version: 0.001
